### ISSUE TITLE
Fonction addEdgeToGraph

### ISSUE THREAD

**Issue by bastienricoeur** [bmirona/graphJava#1]
Je ne comprend pas à quoi sert le edge passé en paramètre de la fonction. Pouvez vous m'expliquer ? :)

**Comment by Tombean** [comment]
Cette fonction ajoute le point de départ et d'arrivée, ainsi que l'objet Edge correspondant à ton type Graph. Par exemple
- si tu utilises une liste d'adjacence , ça ajoute ces 3 données dans la liste
- si tu utilises une matrice, ça pourra ajouter l'objet Edge à l'intersection de la colonne sourceVertex et de la ligne targetVertex.
