### ISSUE TITLE
Where is the documentation ?

### ISSUE THREAD

**Issue by maxcabourg** [bmirona/graphJava#2]
Where can I have a look at the documentation online ? I mean without having to use the .jar

**Comment by maxcabourg** [comment]
Plus I don't think that vertices need to have 2 coordinates. Maybe for later but for now, that makes the algorithm almost impossible to code for me.

**Comment by Tombean** [comment]
L'objet Vertex ne prend pas un nombre fixe de coordonnées. Tout tableau de coordonnées ( en double ) de taille supérieure ou égale à 1 sera accepté par le constructeur. Le Vertex peut ainsi etre valide quelle que soit la dimension choisie ( 1D, 2D, 3D, etc ).

**Comment by maxcabourg** [comment]
D'accord, merci bien de cette information. Cela me simplifiera la tâche !
