### ISSUE TITLE
Probleme type de retour

### ISSUE THREAD

**Issue by maxcabourg** [bmirona/graphJava#3]
Votre fonction getEdge est supposée renvoyée une Edge sauf que comme elle est abstraite je ne peux pas l'instancier.

**Comment by Tombean** [comment]
Aucune de mes méthodes n'a été déclarée abstraite. Désolé, l'erreur ne dois pas venir de là

**Comment by maxcabourg** [comment]
Oui mais je parlais de la classe Edge etant abstraite, pas la méthode.

**Comment by Tombean** [comment]
Tu ne dois pas utilise Edge directement, mais DirectedEdge et UndirectedEdge
